apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    project: roboshop
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        app: mongodb
        tier: db
    spec:
      containers:
        - name: mongo
          image: rajakuma/mongodb:1.0.0
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-port
spec:
  selector:
    project: roboshop
    app: mongodb
    tier: db
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017