apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: roboshop
  labels:
    app: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
        - name: user
          image: rajakuma/user:2.0.0
          envFrom:
            - configMapRef:
                name: user-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: roboshop
spec:
  selector:
    labels:
      app: user
      tier: app
      project: roboshop
  ports:
    - name: user-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: roboshop
data:
  MONGO: "true" # keep true in double quotes
  MONGO_URL: "mongodb://mongodb:27017/user"  # protocol//service-name:service-port/schema
  REDIS_HOST: "redis"


